import { Product } from "./types";

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "iPhone 15 Pro",
    slug: "iphone-15-pro",
    description:
      "The most powerful iPhone ever. Featuring the A17 Pro chip, a game-changing titanium design, and the most advanced camera system ever in an iPhone.",
    price: 24999,
    compareAtPrice: 27999,
    availability: "available",
    condition: "new",
    storage: "256GB",
    color: "Natural Titanium",
    colorHex: "#9A9A9A",
    images: [],
    warrantyMonths: 24,
    batteryHealth: 100,
    category: "iPhone 15",
    active: true,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "2",
    name: "iPhone 15 Pro",
    slug: "iphone-15-pro-512",
    description:
      "Maximum storage for those who need it all. A17 Pro chip with 512GB of space for all your photos, videos, and apps.",
    price: 27999,
    availability: "available",
    condition: "new",
    storage: "512GB",
    color: "Black Titanium",
    colorHex: "#3D3D3D",
    images: [],
    warrantyMonths: 24,
    batteryHealth: 100,
    category: "iPhone 15",
    active: true,
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "3",
    name: "iPhone 15",
    slug: "iphone-15",
    description:
      "Dynamic Island and a 48MP camera. The iPhone 15 brings you the innovations that matter most.",
    price: 17999,
    compareAtPrice: 19999,
    availability: "available",
    condition: "new",
    storage: "128GB",
    color: "Pink",
    colorHex: "#F8C8DC",
    images: [],
    warrantyMonths: 24,
    batteryHealth: 100,
    category: "iPhone 15",
    active: true,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "4",
    name: "iPhone 14 Pro",
    slug: "iphone-14-pro",
    description:
      "Refurbished to like-new condition. Features Dynamic Island, a 48MP camera, and the A16 Bionic chip.",
    price: 19999,
    compareAtPrice: 24999,
    availability: "available",
    condition: "refurbished",
    storage: "128GB",
    color: "Deep Purple",
    colorHex: "#592F5B",
    images: [],
    warrantyMonths: 12,
    batteryHealth: 92,
    category: "iPhone 14",
    active: true,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "5",
    name: "iPhone 14",
    slug: "iphone-14",
    description:
      "Refurbished iPhone 14 with excellent battery health. Great value for a premium device.",
    price: 13999,
    availability: "available",
    condition: "refurbished",
    storage: "256GB",
    color: "Blue",
    colorHex: "#A3C4E8",
    images: [],
    warrantyMonths: 12,
    batteryHealth: 88,
    category: "iPhone 14",
    active: true,
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "6",
    name: "iPhone 13",
    slug: "iphone-13",
    description:
      "Refurbished iPhone 13 in great condition. A reliable everyday companion with fantastic camera quality.",
    price: 10999,
    compareAtPrice: 12999,
    availability: "available",
    condition: "refurbished",
    storage: "128GB",
    color: "Midnight",
    colorHex: "#2D2D3A",
    images: [],
    warrantyMonths: 6,
    batteryHealth: 85,
    category: "iPhone 13",
    active: true,
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "7",
    name: "iPhone 15 Pro",
    slug: "iphone-15-pro-white",
    description: "Elegant White Titanium finish. The same powerful A17 Pro chip in a stunning new color.",
    price: 24999,
    availability: "available",
    condition: "new",
    storage: "256GB",
    color: "White Titanium",
    colorHex: "#F5F5F5",
    images: [],
    warrantyMonths: 24,
    batteryHealth: 100,
    category: "iPhone 15",
    active: true,
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "8",
    name: "iPhone 15 Plus",
    slug: "iphone-15-plus",
    description: "Big and beautiful. 6.7-inch display with all-day battery life and the power of the A16 chip.",
    price: 20999,
    availability: "available",
    condition: "new",
    storage: "256GB",
    color: "Blue",
    colorHex: "#5DADE2",
    images: [],
    warrantyMonths: 24,
    batteryHealth: 100,
    category: "iPhone 15",
    active: true,
    featured: false,
    createdAt: new Date().toISOString(),
  },
];

export const mockOrders = [
  {
    id: "1",
    orderNumber: "ADV-LXYZ123-AB4C",
    customerName: "Sipho M.",
    phone: "0821234567",
    email: "sipho@example.com",
    deliveryAddress: "123 Main St, KuGompo City, 8001",
    paymentMethod: "whatsapp",
    status: "pending",
    subtotal: 24999,
    deliveryFee: 0,
    total: 24999,
    createdAt: new Date().toISOString(),
    items: [
      {
        id: "1",
        productName: "iPhone 15 Pro 256GB",
        quantity: 1,
        unitPrice: 24999,
        selectedVariant: "Natural Titanium",
      },
    ],
  },
];

export const categories = [
  "All",
  "iPhone 15",
  "iPhone 14",
  "iPhone 13",
  "Accessories",
];